# Generated by Django 4.0.5 on 2022-06-16 12:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_description', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateField(default=datetime.date.today)),
                ('count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_description.color')),
                ('model_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_description.modelcar')),
            ],
        ),
    ]
