# Generated by Django 4.0.5 on 2022-06-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartype",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartype",
                to="car_app.brand",
            ),
        ),
        migrations.AlterField(
            model_name="ordercar",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="car_app.color",
            ),
        ),
        migrations.AlterField(
            model_name="ordercar",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="car_app.cartype",
            ),
        ),
    ]
